version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www/html/
  - source: cards/
    destination: /var/www/html/cards/

hooks:
  AfterInstall:
    - location: scripts/install_dependencies  # Correct relative path
      timeout: 300
      runas: root
    - location: scripts/start_server  # Correct relative path
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server  # Correct relative path
      timeout: 300
      runas: root
