  
version: 0.0
os: linux

files:
  - source: index.html
    destination: /var/www/html/
  - source: cards/
    destination: /var/www/html/cards/
  - source: scripts/
    destination: /home/ec2-user/scripts/

hooks:
  AfterInstall:
    - location: /home/ec2-user/scripts/install_dependencies
      timeout: 300
      runas: root
    - location: /home/ec2-user/scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /home/ec2-user/scripts/stop_server/kjbhvg
      timeout: 300
      runas: root
